Fixes #140
files-community/Website pull request #206
Opened 2022-05-17 04:19 UTC by babakfp

![Screenshot 2022-05-16 211844](https://user-images.githubusercontent.com/44144724/168728005-98bc9447-dd64-4ea6-a650-415ca21eb06f.png)

2022-05-17 04:28 UTC, TheOnlyTails requested changes
Looks interesting, just use logical units.

2022-05-17 04:28 UTC, TheOnlyTails commented on src/styles/pages/blogPost.scss
> +  margin-left: auto;
```suggestion
  margin-inline: auto;
```

2022-05-17 04:28 UTC, TheOnlyTails commented on src/styles/pages/blogPost.scss
> +  max-width: 100%;
```suggestion
  max-inline-size: 100%;
```

2022-05-31 05:01 UTC, TheOnlyTails reviewed
Looks fine, but I did notice there is a small horizontal scrolling. Could you fix that?

2022-06-01 07:57 UTC, babakfp commented
> Looks fine, but I did notice there is a small horizontal scrolling. Could you fix that?

I didn't find any "horizontal scrolling". Maybe it's caused by the browser itself, sometimes chromes responsive view doesn't work properly and it shows a horizontal scrollbar🤷‍♂️.

2022-06-01 07:58 UTC, babakfp commented
Never mind, I find it. It just doesn't appear in this post ["How to use a custom background in Files"](https://files.community/blog/posts/how-to-use-background-image).

2022-07-31 09:50 UTC, TheOnlyTails approved these changes
lgtm!

2022-07-31 09:51 UTC, merged