Blog: v2.4.30 (don't merge)
files-community/Website pull request #367
Opened 2023-02-05 18:04 UTC by yaira2

## Description

## Motivation and Context

## Screenshots (if appropriate):

2023-02-05 18:15 UTC, TheOnlyTails requested changes

2023-02-05 18:15 UTC, TheOnlyTails commented on src/routes/blog/posts/announcing-files-v2-4-30/+page.md
> +thumbnail: /blog-resources/files-2-4-30/HeroImage.jpg
you put a hypen between `files` and the version number which doesn't exist in the folder name itself.

```suggestion
thumbnail: /blog-resources/files2-4-30/HeroImage.jpg
```

2023-02-05 18:33 UTC, TheOnlyTails approved these changes

2023-02-05 18:38 UTC, yaira2 commented
Update goes live on Tuesday so I'll merge then.

2023-02-06 07:45 UTC, TheOnlyTails approved these changes

2023-02-06 15:58 UTC, merged