Feature: v3.4 updates (draft)
files-community/Website pull request #655
Opened 2024-05-01 21:05 UTC by yaira2

## Description

## Motivation and Context

## Screenshots (if appropriate):

2024-05-01 22:35 UTC, TheOnlyTails requested changes

2024-05-01 22:35 UTC, TheOnlyTails commented on src/layout/FeaturesSection/FeaturesSection.svelte
> +		command: {
```suggestion
		keybinding: {
```

2024-05-01 22:50 UTC, yaira2 commented on src/layout/FeaturesSection/FeaturesSection.svelte
> +		command: {
Thanks!

2024-05-07 15:30 UTC, TheOnlyTails approved these changes

2024-05-07 21:34 UTC, merged